avifenc -q 60 accademy.png accademy.avif
avifenc -q 60 ams_terni.png ams_terni.avif
avifenc -q 60 apericerca2024.png apericerca2024.avif
avifenc -q 60 buchi_neri.jpg buchi_neri.avif
avifenc -q 60 coloti.jpeg coloti.avif
avifenc -q 60 coming_soon.png coming_soon.avif
avifenc -q 60 convert.sh convert.avif
avifenc -q 60 fermiM.png fermiM.avif
avifenc -q 60 fisicaShow.png fisicaShow.avif
avifenc -q 60 giantS.png giantS.avif
avifenc -q 60 giantS.png.webp giantS.png.avif
avifenc -q 60 giochi.png giochi.avif
avifenc -q 60 icd.png icd.avif
avifenc -q 60 icd2023.png icd2023.avif
avifenc -q 60 icd2024.png icd2024.avif
avifenc -q 60 inf_picc.png inf_picc.avif
avifenc -q 60 lab2go2023.png lab2go2023.avif
avifenc -q 60 lab2go2024.jpeg lab2go2024.avif
avifenc -q 60 Onde-gravitazionali.jpg Onde-gravitazionali.avif
avifenc -q 60 onde.png onde.avif
avifenc -q 60 orientamento2025.png orientamento2025.avif
avifenc -q 60 particelleNebbia.png particelleNebbia.avif
avifenc -q 60 seminario2023sharper.png seminario2023sharper.avif
avifenc -q 60 seminarioMiguel.png seminarioMiguel.avif
avifenc -q 60 stelle_galassie_universo.png stelle_galassie_universo.avif
avifenc -q 60 volantino_stelle_galassie_universo.png volantino_stelle_galassie_universo.avif
