avifenc -q 60 3punti.png 3punti.avif
avifenc -q 60 coloti_sfondo.png coloti_sfondo.avif
avifenc -q 60 coloti.png coloti.avif
avifenc -q 60 down.png down.avif
avifenc -q 60 favicon.ico favicon.avif
avifenc -q 60 favicon.png favicon.avif
avifenc -q 60 infografica copia.png infografica copia.avif
avifenc -q 60 infografica_phone.png infografica_phone.avif
avifenc -q 60 infografica_tablet.png infografica_tablet.avif
avifenc -q 60 infografica.avif infografica.avif
avifenc -q 60 infografica.png infografica.avif
avifenc -q 60 lab2go_studenti.png lab2go_studenti.avif
avifenc -q 60 lab2go.png lab2go.avif
avifenc -q 60 lodo dip eccellenza 600x600.png lodo dip eccellenza 600x600.avif
avifenc -q 60 logo_big.png logo_big.avif
avifenc -q 60 logo_dip_ecc.png logo_dip_ecc.avif
avifenc -q 60 logo_unipg_SC_altaRis.png logo_unipg_SC_altaRis.avif
avifenc -q 60 logo_unipg_SC.png logo_unipg_SC.avif
avifenc -q 60 logo_unipg.svg logo_unipg.avif
avifenc -q 60 logo.png logo.avif
avifenc -q 60 og_sfondo.png og_sfondo.avif
avifenc -q 60 OG.png OG.avif
avifenc -q 60 onde_grav_foligno.jpeg onde_grav_foligno.avif
avifenc -q 60 organigramma.png organigramma.avif
avifenc -q 60 pianeti_alta_ris.png pianeti_alta_ris.avif
avifenc -q 60 pianeti_sfondo.png pianeti_sfondo.avif
avifenc -q 60 pianeti.png pianeti.avif
avifenc -q 60 pianetologia_sfondo.png pianetologia_sfondo.avif
avifenc -q 60 pianetologia.png pianetologia.avif
avifenc -q 60 progetto_gif.gif progetto_gif.avif
avifenc -q 60 rc_sfondo.png rc_sfondo.avif
avifenc -q 60 rc.png rc.avif
avifenc -q 60 read_astro.png read_astro.avif
avifenc -q 60 read_more_btn.png read_more_btn.avif
avifenc -q 60 risultati_gif.gif risultati_gif.avif
avifenc -q 60 seminario_universo.png seminario_universo.avif
avifenc -q 60 sharper_perugia.jpeg sharper_perugia.avif
avifenc -q 60 sharper_perugia.png sharper_perugia.avif
avifenc -q 60 Super_C_scritta.png Super_C_scritta.avif
avifenc -q 60 team_gif.gif team_gif.avif
avifenc -q 60 una_notte_coloti.jpeg una_notte_coloti.avif
avifenc -q 60 up.png up.avif
avifenc -q 60 work_in_progress.png work_in_progress.avif
